// prisma/seed.js
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

const products = [
  {
    name: "Premium Wireless Headphones",
    slug: "wireless-headphones",
    description: "Experience premium sound quality with our flagship wireless headphones. Featuring active noise cancellation, 40-hour battery life, and ultra-comfortable memory foam ear cushions.",
    price: 249.99,
    originalPrice: 349.99,
    rating: 4.8,
    reviewCount: 128,
    stock: 15,
    brand: "AudioPro",
    category: "Electronics",
    badge: "Best Seller",
    images: ["/wireless-headphones.jpg", "/wireless-headphones.jpg"],
    colors: ["Black", "Silver", "Navy"],
    sizes: [],
    features: ["Noise Cancellation", "40h Battery", "Wireless"],
    isFeatured: true
  },
  {
    name: "Series 7 Smart Watch",
    slug: "smart-watch-series-7",
    description: "The next generation of wearable technology. Track fitness, monitor health, and stay connected with a stunning always-on Retina display.",
    price: 399.00,
    originalPrice: 449.00,
    rating: 4.6,
    reviewCount: 256,
    stock: 10,
    brand: "TechWear",
    category: "Electronics",
    badge: "New",
    images: ["/smart-watch.jpg", "/smart-watch.jpg"],
    colors: ["Silver", "Graphite", "Gold"],
    sizes: ["40mm", "44mm"],
    features: ["Water Resistant", "ECG App", "Always-on Display"],
    isFeatured: true
  },
  {
    name: "Pro Gaming Laptop 15",
    slug: "pro-gaming-laptop-15",
    description: "Dominate the competition with the latest RTX 4080 graphics and i9 processor. 240Hz display for buttery smooth gameplay.",
    price: 1899.00,
    originalPrice: 2199.00,
    rating: 4.9,
    reviewCount: 45,
    stock: 5,
    brand: "GamerX",
    category: "Electronics",
    badge: "Top Rated",
    images: ["/laptop.jpg"],
    colors: ["Matte Black", "Lunar White"],
    sizes: ["15-inch"],
    features: ["RTX 4080", "32GB RAM", "1TB SSD"],
    isFeatured: true
  },
  {
    name: "4K Ultra HD Monitor",
    slug: "4k-ultra-hd-monitor",
    description: "Crystal clear picture quality with 100% sRGB color accuracy. Perfect for creators and professionals.",
    price: 499.00,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 89,
    stock: 20,
    brand: "VisionDisplay",
    category: "Electronics",
    badge: "",
    images: ["/monitor.jpg"],
    colors: ["Black"],
    sizes: ["27-inch", "32-inch"],
    features: ["IPS Panel", "USB-C Hub", "HDR10"],
    isFeatured: false
  },
  {
    name: "Mechanical Keyboard RGB",
    slug: "mechanical-keyboard-rgb",
    description: "Tactile mechanical switches with customizable RGB lighting. Durable aluminum frame built to last.",
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.7,
    reviewCount: 210,
    stock: 30,
    brand: "KeyMaster",
    category: "Electronics",
    badge: "Sale",
    images: ["/keyboard.jpg"],
    colors: ["Black", "White"],
    sizes: [],
    features: ["Blue Switches", "RGB Backlight", "Macro Keys"],
    isFeatured: false
  },
  {
    name: "Italian Leather Crossbody Bag",
    slug: "leather-bag",
    description: "Handcrafted from premium Italian full-grain leather, this crossbody bag combines timeless elegance with everyday practicality.",
    price: 189.00,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 64,
    stock: 8,
    brand: "Artisan",
    category: "Accessories",
    badge: "Luxury",
    images: ["/leather-bag.jpg", "/leather-bag.jpg"],
    colors: ["Cognac", "Black"],
    sizes: [],
    features: ["Full-grain Leather", "Magnetic Closure"],
    isFeatured: true
  },
  {
    name: "Classic Aviator Sunglasses",
    slug: "classic-aviator-sunglasses",
    description: "Timeless aviator style with polarized lenses for maximum UV protection.",
    price: 159.00,
    originalPrice: 199.00,
    rating: 4.7,
    reviewCount: 142,
    stock: 50,
    brand: "VisionX",
    category: "Accessories",
    badge: "",
    images: ["/sunglasses.jpg"],
    colors: ["Gold/Green", "Silver/Blue"],
    sizes: ["Standard", "Large"],
    features: ["Polarized", "UV Protection"],
    isFeatured: false
  },
  {
    name: "Minimalist Laptop Backpack",
    slug: "minimalist-laptop-backpack",
    description: "Designed for the modern commuter. Features a padded 15-inch laptop sleeve and water-resistant exterior.",
    price: 119.00,
    originalPrice: 159.00,
    rating: 4.5,
    reviewCount: 93,
    stock: 18,
    brand: "UrbanPack",
    category: "Accessories",
    badge: "Sale",
    images: ["/backpack.jpg"],
    colors: ["Charcoal", "Olive"],
    sizes: [],
    features: ["Water Resistant", "Laptop Sleeve"],
    isFeatured: false
  },
  {
    name: "Leather Wallet",
    slug: "leather-wallet",
    description: "Slim bifold wallet made from genuine leather. RFID blocking technology to keep your cards safe.",
    price: 49.99,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 300,
    stock: 100,
    brand: "Artisan",
    category: "Accessories",
    badge: "Best Seller",
    images: ["/wallet.jpg"],
    colors: ["Brown", "Black"],
    sizes: [],
    features: ["RFID Blocking", "Slim Design"],
    isFeatured: false
  },

  {
    name: "Ultralight Running Shoes",
    slug: "running-shoes",
    description: "Engineered for speed and comfort. Featuring responsive foam cushioning and breathable knit upper.",
    price: 129.99,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 89,
    stock: 25,
    brand: "SwiftRun",
    category: "Footwear",
    badge: "New",
    images: ["/running-shoes.jpg", "/running-shoes.jpg"],
    colors: ["White/Gray", "Black/Red"],
    sizes: ["7", "8", "9", "10", "11"],
    features: ["Lightweight", "Breathable"],
    isFeatured: true
  },
  {
    name: "Classic Canvas Sneakers",
    slug: "classic-canvas-sneakers",
    description: "The everyday sneaker that goes with everything. Durable canvas upper and rubber sole.",
    price: 59.99,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 500,
    stock: 40,
    brand: "StreetWalk",
    category: "Footwear",
    badge: "",
    images: ["/running-shoes1.jpg"],
    colors: ["White", "Black", "Navy"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    features: ["Vulcanized Rubber", "Comfort Insole"],
    isFeatured: false
  },
  {
    name: "Hiking Boots Waterproof",
    slug: "hiking-boots-waterproof",
    description: "Rugged hiking boots designed for the toughest trails. Waterproof membrane keeps feet dry.",
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.8,
    reviewCount: 75,
    stock: 12,
    brand: "TrailMaster",
    category: "Footwear",
    badge: "Durable",
    images: ["/boots.jpg"],
    colors: ["Earth", "Charcoal"],
    sizes: ["8", "9", "10", "11", "12"],
    features: ["Waterproof", "High Traction"],
    isFeatured: false
  },
  {
    name: "Premium Cotton Essential Tee",
    slug: "premium-cotton-tee",
    description: "Your new favorite t-shirt. Made from 100% organic cotton that gets softer with every wash.",
    price: 49.99,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 312,
    stock: 100,
    brand: "BasicCo",
    category: "Fashion",
    badge: "Best Value",
    images: ["/tshirt.jpg"],
    colors: ["White", "Black", "Navy", "Gray"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    features: ["100% Organic Cotton", "Pre-shrunk"],
    isFeatured: false
  },
  {
    name: "Denim Trucker Jacket",
    slug: "denim-trucker-jacket",
    description: "Classic denim jacket with a vintage wash. Perfect for layering in any season.",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.7,
    reviewCount: 150,
    stock: 20,
    brand: "UrbanDenim",
    category: "Fashion",
    badge: "",
    images: ["/jacket.jpg"],
    colors: ["Light Wash", "Dark Wash"],
    sizes: ["S", "M", "L", "XL"],
    features: ["100% Cotton", "Vintage Fit"],
    isFeatured: true
  },
  {
    name: "Slim Fit Chino Pants",
    slug: "slim-fit-chino-pants",
    description: "Versatile chinos that work for office or weekend. Stretch fabric for all-day comfort.",
    price: 69.99,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 80,
    stock: 35,
    brand: "BasicCo",
    category: "Fashion",
    badge: "",
    images: ["/chinos.jpg"],
    colors: ["Khaki", "Navy", "Olive"],
    sizes: ["30", "32", "34", "36"],
    features: ["Stretch Fabric", "Slim Fit"],
    isFeatured: false
  },

  // --- Lifestyle ---
  {
    name: "Handcrafted Ceramic Mug",
    slug: "handcrafted-ceramic-mug",
    description: "Each mug is individually thrown on the wheel and hand-glazed, making every piece unique.",
    price: 34.99,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 47,
    stock: 12,
    brand: "CeramicArts",
    category: "Lifestyle",
    badge: "Handmade",
    images: ["/ceramic-mug.jpg"],
    colors: ["Earth Tone", "Ocean Blue"],
    sizes: ["12oz"],
    features: ["Dishwasher Safe", "Lead-free Glaze"],
    isFeatured: false
  },
  {
    name: "Eco-Friendly Yoga Mat",
    slug: "eco-friendly-yoga-mat",
    description: "Non-slip yoga mat made from natural rubber. Perfect cushioning for your practice.",
    price: 59.99,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 112,
    stock: 25,
    brand: "ZenLife",
    category: "Lifestyle",
    badge: "Eco",
    images: ["/yogamat.jpg"],
    colors: ["Purple", "Teal"],
    sizes: ["Standard"],
    features: ["Non-slip", "Natural Rubber"],
    isFeatured: false
  },
  {
    name: "Stainless Steel Water Bottle",
    slug: "stainless-water-bottle",
    description: "Double-walled vacuum insulation keeps drinks cold for 24 hours or hot for 12 hours.",
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.7,
    reviewCount: 400,
    stock: 60,
    brand: "HydroGear",
    category: "Lifestyle",
    badge: "",
    images: ["/bottle.jpg"],
    colors: ["Matte Black", "White", "Blue"],
    sizes: ["24oz", "32oz"],
    features: ["BPA Free", "Insulated"],
    isFeatured: false
  },
  {
    name: "Modern Desk Lamp",
    slug: "modern-desk-lamp",
    description: "Minimalist LED desk lamp with adjustable brightness and color temperature.",
    price: 45.00,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 55,
    stock: 15,
    brand: "HomeDeco",
    category: "Lifestyle",
    badge: "",
    images: ["/lamp.jpg"],
    colors: ["Black", "White"],
    sizes: [],
    features: ["Touch Control", "USB Charging Port"],
    isFeatured: false
  },
  {
    name: "Aromatherapy Diffuser",
    slug: "aromatherapy-diffuser",
    description: "Ultrasonic essential oil diffuser with ambient light settings. Creates a calming atmosphere.",
    price: 39.99,
    originalPrice: null,
    rating: 4.5,
    reviewCount: 98,
    stock: 30,
    brand: "ZenLife",
    category: "Lifestyle",
    badge: "",
    images: ["/diffuser.jpg"],
    colors: ["Wood Grain", "White"],
    sizes: ["300ml"],
    features: ["Auto Shut-off", "Silent Operation"],
    isFeatured: false
  }
]

async function main() {
  console.log('Start seeding ...')

  // Purana data clear karein
  await prisma.product.deleteMany()
  await prisma.orderItem.deleteMany()
  await prisma.order.deleteMany()

  for (const product of products) {
    const createdProduct = await prisma.product.create({
      data: product,
    })
    console.log(`Created product: ${createdProduct.name}`)
  }
  console.log('Seeding finished.')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })